# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: matrix_multiply.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15matrix_multiply.proto\x12\x06matrix\"\x9d\x01\n\rMatrixRequest\x12\x16\n\x0ematrix1_values\x18\x01 \x03(\x12\x12\x16\n\x0ematrix1_height\x18\x02 \x01(\r\x12\x15\n\rmatrix1_width\x18\x03 \x01(\r\x12\x16\n\x0ematrix2_values\x18\x04 \x03(\x12\x12\x16\n\x0ematrix2_height\x18\x05 \x01(\r\x12\x15\n\rmatrix2_width\x18\x06 \x01(\r\"\'\n\x0eMatrixResponse\x12\x15\n\rresult_values\x18\x01 \x03(\x12\x32L\n\x0fMatrixOperation\x12\x39\n\x08Multiply\x12\x15.matrix.MatrixRequest\x1a\x16.matrix.MatrixResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'matrix_multiply_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MATRIXREQUEST']._serialized_start=34
  _globals['_MATRIXREQUEST']._serialized_end=191
  _globals['_MATRIXRESPONSE']._serialized_start=193
  _globals['_MATRIXRESPONSE']._serialized_end=232
  _globals['_MATRIXOPERATION']._serialized_start=234
  _globals['_MATRIXOPERATION']._serialized_end=310
# @@protoc_insertion_point(module_scope)
